### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Boszacta-Emil** [dramorak/dramorak.github.io#1]
This project doesn't have a license.

I suggest using [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html), or [Apache 2](https://www.apache.org/licenses/LICENSE-2.0.html).

I'd also recommend adding a license to your other projects.

**Comment by The-Emil** [comment]
I can make a Pull Request with a license and notices, if requested.

**Comment by dramorak** [comment]
Hey! Thanks for letting me know.

I intended for it to be totally open anyway, glad it's formal now.

**Comment by Boszacta-Emil** [comment]
Thanks!
